/// Expect:
/// - error: "Call to function that may throw needs to be in a try statement or a function marked as throws"

fn my_format(value: i64) -> String => format("value is {}", value)

fn main() {
    println("{}", my_format(value: 42))
}

// Fixes #517.
