/// Expect:
/// - error: "Call to function that may throw needs to be in a try statement or a function marked as throws"

function my_format(value: i64) => format("value is {}", value)

function main() {
    println("{}", my_format(value: 42))
}

// Fixes #517.
