/// Expect:
/// - output: "PASS\n"

fn troublemaker() throws -> i64 {
    throw Error::from_errno(1)
}

fn main() {
    let opt: i64? = None
    try {
        let foo = opt ?? troublemaker()
        println("FAIL")
    } catch {
        println("PASS")
    }
}
